package io.roastedroot.protobuf4j.test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import com.google.protobuf.compiler.PluginProtos;
import io.roastedroot.zerofs.Configuration;
import io.roastedroot.zerofs.ZeroFs;
import java.nio.file.FileSystem;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicReference;
import org.junit.jupiter.api.Test;

public abstract class AbstractSubprocessInjectionTest {

    protected abstract ProtobufTestAdapter createAdapter(Path workdir);

    @Test
    public void shouldInvokeMockSubprocessForExternalPlugin() throws Exception {
        FileSystem fs =
                ZeroFs.newFileSystem(
                        Configuration.unix().toBuilder().setAttributeViews("unix").build());
        var workdir = fs.getPath(".");
        Files.write(
                workdir.resolve("test.proto"),
                ("syntax = \"proto3\";\n"
                                + "package test;\n"
                                + "message Foo { string name = 1; }\n")
                        .getBytes());

        var called = new AtomicBoolean(false);
        var receivedProgramName = new AtomicReference<String>();

        var adapter = createAdapter(workdir);
        int exitCode =
                adapter.runProtoc(
                        List.of("--plugin=protoc-gen-mock", "--mock_out=.", "test.proto"),
                        Map.of(),
                        workdir,
                        (programName, request) -> {
                            called.set(true);
                            receivedProgramName.set(programName);

                            return PluginProtos.CodeGeneratorResponse.newBuilder()
                                    .addFile(
                                            PluginProtos.CodeGeneratorResponse.File.newBuilder()
                                                    .setName("test/mock_generated.txt")
                                                    .setContent("// Generated by mock plugin"))
                                    .build();
                        });

        assertEquals(0, exitCode);
        assertTrue(called.get(), "Mock subprocess should have been invoked");
        assertTrue(
                receivedProgramName.get().contains("protoc-gen-mock"),
                "Program name should contain protoc-gen-mock but was: "
                        + receivedProgramName.get());
        assertTrue(
                Files.exists(workdir.resolve("test/mock_generated.txt")),
                "Mock plugin output file should exist");
    }
}
